import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read=(p)=>readFile(new URL(`../../${p}`,import.meta.url),'utf8');

test('central research config separates QA and official study',async()=>{const s=await read('src/config/researchConfig.ts');for(const token of ['APULAB-QA-2026','APULAB-STUDY-2026','apulab-telemetry-v2','apulab-protocol-2026-v1','APULAB-STUDY-RC.1','VITE_GIT_COMMIT_SHA'])assert.match(s,new RegExp(token));assert.match(s,/export type StudyCondition = 'game';/)});
test('Station active research layer is game-only',async()=>{for(const path of ['src/config/researchConfig.ts','src/systems/SessionService.ts','src/systems/research/MockResearchRepository.ts','scripts/research/create-study-participants.ts','supabase/functions/ingest-telemetry/index.ts','docs/research/data-dictionary.md','docs/research/database-schema.md','docs/research/study-freeze-checklist.md','docs/research/supabase-migration.md']){const s=await read(path);assert.doesNotMatch(s,/static_control/,`active Station file still references non-game condition: ${path}`)}});
test('SessionService rejects a non-game assignment before creating GameState session',async()=>{const s=await read('src/systems/SessionService.ts');const guard=s.indexOf("String(auth.data.study_condition) !== 'game'");const state=s.indexOf('const state = GameState.getInstance()',guard);assert.ok(guard>=0,'Station frontend condition guard missing');assert.ok(state>guard,'condition guard must run before GameState session creation')});
test('mock repository can return only game condition',async()=>{const s=await read('src/systems/research/MockResearchRepository.ts');assert.match(s,/=== 'game' \? 'game' : null/);assert.doesNotMatch(s,/static_control/)});
test('official generator requires an explicit codes file and creates game assignments',async()=>{const s=await read('scripts/research/create-study-participants.ts');for(const token of ['--codes-file=','codes_file_contains_duplicates','invalid_station_game_code','APULAB-STUDY-2026',"'game'",'manual_protocol'])assert.ok(s.includes(token),`missing Station generator guard: ${token}`);assert.doesNotMatch(s,/--count=/)});
test('event registry covers implemented N1 through N7 and storage diagnostics',async()=>{const s=await read('src/research/telemetry/events.ts');for(const token of ['battery_power_changed','multimeter_mode_changed','battery_measured','command_moved','collision_detected','repeat_unlocked','scan_completed','sample_reached','communication_point_reached','data_sent','storage_pressure'])assert.match(s,new RegExp(token));assert.match(s,/final_point_reached: 'communication_point_reached'/)});
test('PII guard blocks raw codes and child-identifying fields',async()=>{const s=await read('src/research/telemetry/payloads.ts');for(const token of ['participant_code','study_code','parent_name','birth_date','school','screenshot','html'])assert.match(s,new RegExp(token))});
test('database migrations separate official paper data and harden views',async()=>{const v2=await read('supabase/migrations/20260906170000_research_schema_v2.sql');const h=await read('supabase/migrations/20260906183000_research_hardening.sql');const m6=await read('supabase/migrations/20260907230000_station_game_condition_guard.sql');assert.match(v2,/study_id='APULAB-STUDY-2026' AND environment='study'/);assert.match(v2,/ENABLE ROW LEVEL SECURITY/);for(const token of ['expected_commit_sha','sync_token_hash','count(e.event_id)','to_instrument','REVOKE ALL ON TABLE v_session_quality'])assert.ok(h.includes(token),`missing migration token: ${token}`);for(const token of ['apulab_station_assignments_game_only','apulab_station_sessions_game_only','apulab_station_events_game_only',"study_condition = 'game'"])assert.ok(m6.includes(token),`missing Migration 6 token: ${token}`)});
test('edge auth uses HMAC, durable session auth and Station game-only guards',async()=>{const s=await read('supabase/functions/ingest-telemetry/index.ts');for(const token of ['APULAB_AUTH_PEPPER','APULAB_SESSION_PROOF_SECRET','pbkdf2_sha256','session_sync_token_invalid','session_identity_conflict','study_not_active','study_build_mismatch','study_commit_mismatch','event_level_mismatch','authentication_cooldown','station_condition_mismatch'])assert.match(s,new RegExp(token));assert.match(s,/type StudyCondition = 'game';/);assert.match(s,/proof\.study_condition !== 'game'/);assert.doesNotMatch(s,/static_control|participant_auth_not_configured/)});
test('browser invocation explicitly disables platform JWT because app-level auth is enforced',async()=>{const s=await read('supabase/config.toml');assert.match(s,/\[functions\.ingest-telemetry\]/);assert.match(s,/verify_jwt\s*=\s*false/)});
test('external questionnaires are documented as external and not runtime screens',async()=>{const s=await read('docs/research/supabase-migration.md');assert.match(s,/PRE, POST and MEEGA\+KIDS remain external forms/)});
test('environment file contains no committed values for server secrets',async()=>{const s=await read('.env.example');for(const key of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','APULAB_AUTH_PEPPER','APULAB_SESSION_PROOF_SECRET'])assert.match(s,new RegExp(`^${key}=$`,'m'))});
test('N1-N4 research patch uses real runtime handlers rather than fixed canvas inference',async()=>{const s=await read('scripts/patch-mission01-research-telemetry.mjs');for(const token of ['toggleBattery','toggleMultimeter','measurementKind','probe_drag_start','setActiveBattery','handleBatteryChoice','dropAt(index)','command_executed'])assert.ok(s.includes(token),`missing real-handler marker: ${token}`);assert.doesNotMatch(s,/const P=\{battery:/)});
test('SyncService has complete serialized reentrant drain and explicit flush',async()=>{const s=await read('src/systems/SyncService.ts');for(const token of ['rerunRequested','drainUntilStable','static async flush','this.rerunRequested = true'])assert.ok(s.includes(token),`missing sync drain token: ${token}`);assert.match(s,/if \(this\.activePromise\)/)});
test('Mission 01 bridge has one canonical iframe authority and rejects foreign source/origin',async()=>{const bridge=await read('src/systems/Mission01TelemetryBridge.ts');const screen=await read('src/ui/Mission01Screen.ts');assert.match(bridge,/document\.querySelector<HTMLIFrameElement>\('\.mission01-frame'\)/);assert.match(bridge,/message\.origin !== window\.location\.origin/);assert.match(bridge,/message\.source !== frame\.contentWindow/);assert.match(screen,/frame\.className = 'mission01-frame'/)});
test('N7 pre-hardening research semantics converts legacy arrival to exact-cell canonical arrival and rejects auto-send',async()=>{const s=await read('scripts/patch-mission01-level7-research-semantics.mjs');assert.match(s,/roverState\.c===sampleCell\.c&&roverState\.r===sampleCell\.r/);assert.match(s,/const finalEmission="recordLevel7Event\('final_point_reached'/);assert.match(s,/replaceAll\(finalEmission,"recordLevel7Event\('communication_point_reached'/);assert.match(s,/auto_data_sent_forbidden/);assert.match(s,/communication arrival only · no auto-send/)});
test('N7 final hardening requires exact sample, communication arrival and explicit send',async()=>{const s=await read('scripts/patch-mission01-level7-final-hardening.mjs');for(const token of ['const isAtSample=()=>roverState.c===sampleCell.c&&roverState.r===sampleCell.r','data-command="send"','communicationPointReached=false','dataSent=false',"recordLevel7Event('communication_point_reached'", "recordLevel7Event('data_sent'",'PASO 5 · ENVÍA LOS DATOS'])assert.ok(s.includes(token),`missing final hardening token: ${token}`);assert.match(s,/for \(const forbidden of \['PUNTO FINAL','final_point_reached','isAdjacentToSample','junto a la muestra'\]\)/)});
test('mock-only QA hooks cannot be installed in Supabase mode',async()=>{const s=await read('src/main.ts');assert.match(s,/if \(getDataMode\(\) !== 'mock'\) return/);assert.match(s,/apulabResearchQA/)});
test('export script paginates with exact count and writes only into private output',async()=>{const s=await read('scripts/research/export-telemetry.ts');for(const token of ['Range: `${offset}-${end}`','Prefer: \'count=exact\'','export_count_mismatch','.private'])assert.ok(s.includes(token),`missing export guard: ${token}`)});
