import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read=(p)=>readFile(new URL(`../../${p}`,import.meta.url),'utf8');

test('central research config separates QA and official study',async()=>{const s=await read('src/config/researchConfig.ts');for(const token of ['APULAB-QA-2026','APULAB-STUDY-2026','apulab-telemetry-v2','apulab-protocol-2026-v1','APULAB-STUDY-RC.1','VITE_GIT_COMMIT_SHA'])assert.match(s,new RegExp(token))});
test('event registry covers implemented N1 through N7 and storage diagnostics',async()=>{const s=await read('src/research/telemetry/events.ts');for(const token of ['battery_power_changed','multimeter_mode_changed','battery_measured','command_moved','collision_detected','repeat_unlocked','scan_completed','sample_reached','communication_point_reached','data_sent','storage_pressure'])assert.match(s,new RegExp(token));assert.match(s,/final_point_reached: 'communication_point_reached'/)});
test('PII guard blocks raw codes and child-identifying fields',async()=>{const s=await read('src/research/telemetry/payloads.ts');for(const token of ['participant_code','study_code','parent_name','birth_date','school','screenshot','html'])assert.match(s,new RegExp(token))});
test('database migrations separate official paper data and harden views',async()=>{const v2=await read('supabase/migrations/20260906170000_research_schema_v2.sql');const h=await read('supabase/migrations/20260906183000_research_hardening.sql');assert.match(v2,/study_id='APULAB-STUDY-2026' AND environment='study'/);assert.match(v2,/ENABLE ROW LEVEL SECURITY/);for(const token of ['expected_commit_sha','sync_token_hash','count(e.event_id)','to_instrument','REVOKE ALL ON TABLE v_session_quality'])assert.ok(h.includes(token),`missing migration token: ${token}`)});
test('edge auth uses HMAC, app proof at authentication, durable session token and immutable study metadata',async()=>{const s=await read('supabase/functions/ingest-telemetry/index.ts');for(const token of ['APULAB_AUTH_PEPPER','APULAB_SESSION_PROOF_SECRET','pbkdf2_sha256','session_sync_token_invalid','session_identity_conflict','study_not_active','study_build_mismatch','study_commit_mismatch','event_level_mismatch','authentication_cooldown'])assert.match(s,new RegExp(token));assert.doesNotMatch(s,/participant_auth_not_configured/)});
test('browser invocation explicitly disables platform JWT because app-level auth is enforced',async()=>{const s=await read('supabase/config.toml');assert.match(s,/\[functions\.ingest-telemetry\]/);assert.match(s,/verify_jwt\s*=\s*false/)});
test('external questionnaires are documented as external and not runtime screens',async()=>{const s=await read('docs/research/supabase-migration.md');assert.match(s,/PRE, POST and MEEGA\+KIDS remain external forms/)});
test('environment file contains no committed values for server secrets',async()=>{const s=await read('.env.example');for(const key of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','APULAB_AUTH_PEPPER','APULAB_SESSION_PROOF_SECRET'])assert.match(s,new RegExp(`^${key}=$`,'m'))});
test('N1-N4 research patch uses real runtime handlers rather than fixed canvas inference',async()=>{const s=await read('scripts/patch-mission01-research-telemetry.mjs');for(const token of ['toggleBattery','toggleMultimeter','measurementKind','probe_drag_start','setActiveBattery','handleBatteryChoice','dropAt(index)','command_executed'])assert.ok(s.includes(token),`missing real-handler marker: ${token}`);assert.doesNotMatch(s,/const P=\{battery:/)});
test('N7 research sample event is exact-cell only',async()=>{const s=await read('scripts/patch-mission01-level7-research-semantics.mjs');assert.match(s,/roverState\.c===sampleCell\.c&&roverState\.r===sampleCell\.r/);assert.match(s,/LEVEL 7 RESEARCH SEMANTICS OK · exact sample tile/)});
