import * as THREE from 'three';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';

export interface RoverOptions { name: string; bodyTint?: number; }

const C={panel:0x13213c,panel2:0xa1adbf,frame:0x1d212a,tan:0xcac2b7,cream:0xe7e0d6,dark:0x252831,metal:0x666159,bronze:0xc86f10,wheel:0x24252a,black:0x111318,gray:0x4b4e57,orange:0xe08b18,hubDark:0x181a20};
const mat=(color:number,roughness=.82,metalness=.05)=>new THREE.MeshStandardMaterial({color,roughness,metalness,flatShading:true});

function add(g:THREE.BufferGeometry,m:THREE.Material,p:THREE.Object3D,shadow=true):THREE.Mesh{const x=new THREE.Mesh(g,m);x.castShadow=shadow;x.receiveShadow=shadow;p.add(x);return x;}
function box(w:number,h:number,d:number,m:THREE.Material,p:THREE.Object3D,s=true):THREE.Mesh{return add(new THREE.BoxGeometry(w,h,d),m,p,s);}
function rbox(w:number,h:number,d:number,r:number,m:THREE.Material,p:THREE.Object3D,s=true):THREE.Mesh{return add(new RoundedBoxGeometry(w,h,d,1,r),m,p,s);}
function cyl(rt:number,rb:number,h:number,n:number,m:THREE.Material,p:THREE.Object3D,s=true):THREE.Mesh{return add(new THREE.CylinderGeometry(rt,rb,h,n),m,p,s);}
function beam(a:THREE.Vector3,b:THREE.Vector3,t:number,m:THREE.Material,p:THREE.Object3D):THREE.Mesh{const mid=a.clone().add(b).multiplyScalar(.5),len=a.distanceTo(b),q=box(t,len,t,m,p);q.position.copy(mid);q.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return q;}
function jointX(r:number,depth:number,m:THREE.Material,p:THREE.Object3D,pos:THREE.Vector3):THREE.Mesh{const j=cyl(r,r,depth,8,m,p);j.position.copy(pos);j.rotation.z=Math.PI/2;return j;}

function panelShape(w:number,d:number,cut=.22):THREE.Shape{const s=new THREE.Shape();s.moveTo(-w/2+cut,-d/2);s.lineTo(w/2-cut,-d/2);s.lineTo(w/2,-d/2+cut);s.lineTo(w/2,d/2-cut);s.lineTo(w/2-cut,d/2);s.lineTo(-w/2+cut,d/2);s.lineTo(-w/2,d/2-cut);s.lineTo(-w/2,-d/2+cut);s.closePath();return s;}
function normalizePanelUV(geo:THREE.BufferGeometry,w:number,d:number):void{const pos=geo.attributes.position as THREE.BufferAttribute,uv=new Float32Array(pos.count*2);for(let i=0;i<pos.count;i++){uv[i*2]=THREE.MathUtils.clamp((pos.getX(i)+w/2)/w,0,1);uv[i*2+1]=THREE.MathUtils.clamp((pos.getY(i)+d/2)/d,0,1);}geo.setAttribute('uv',new THREE.BufferAttribute(uv,2));}
function solarTexture():THREE.CanvasTexture{const c=document.createElement('canvas');c.width=768;c.height=512;const x=c.getContext('2d');if(!x)throw new Error('solar_texture_context_missing');x.imageSmoothingEnabled=false;x.fillStyle='#20252f';x.fillRect(0,0,c.width,c.height);const outer=18;x.fillStyle='#0a1428';x.fillRect(outer,outer,c.width-outer*2,c.height-outer*2);const cols=6,rows=4,pad=28,gap=9,areaX=outer+pad,areaY=outer+pad,areaW=c.width-(outer+pad)*2,areaH=c.height-(outer+pad)*2,cellW=(areaW-gap*(cols-1))/cols,cellH=(areaH-gap*(rows-1))/rows;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const px=areaX+col*(cellW+gap),py=areaY+row*(cellH+gap),g=x.createLinearGradient(px,py,px+cellW,py+cellH);g.addColorStop(0,'#284b83');g.addColorStop(.46,'#183866');g.addColorStop(1,'#0d244d');x.fillStyle=g;x.fillRect(px,py,cellW,cellH);x.strokeStyle='rgba(204,220,242,.88)';x.lineWidth=3;x.strokeRect(px+1.5,py+1.5,cellW-3,cellH-3);x.fillStyle='rgba(220,230,245,.55)';x.fillRect(px+cellW*.33,py+7,2.6,cellH-14);x.fillRect(px+cellW*.66,py+7,2.6,cellH-14);x.fillStyle='rgba(112,145,190,.30)';for(let n=1;n<5;n++)x.fillRect(px+6,py+(cellH/5)*n,cellW-12,1.5);}const reflection=x.createLinearGradient(0,0,c.width,c.height);reflection.addColorStop(0,'rgba(255,255,255,0)');reflection.addColorStop(.43,'rgba(255,255,255,0)');reflection.addColorStop(.52,'rgba(202,226,255,.13)');reflection.addColorStop(.61,'rgba(255,255,255,0)');reflection.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=reflection;x.fillRect(0,0,c.width,c.height);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.anisotropy=4;return t;}

export class Rover{
  readonly group=new THREE.Group();readonly deck=new THREE.Group();readonly mast=new THREE.Group();readonly dish=new THREE.Group();readonly antenna=new THREE.Group();readonly wheelGroups:THREE.Group[]=[];readonly eyeMaterials:THREE.MeshStandardMaterial[]=[];readonly powerMaterials:THREE.MeshStandardMaterial[]=[];readonly cameraBar:THREE.Mesh;readonly detachableSolarPanel:THREE.Group;
  private readonly wheelPositions:THREE.Vector3[]=[];private readonly detachableBasePosition:THREE.Vector3;private readonly detachableBaseRotation:THREE.Euler;private readonly detachableBaseScale:THREE.Vector3;private wheelSpin=0;

  constructor(options:RoverOptions){
    this.group.name=options.name;this.group.position.y=1.80;
    const M={panel:mat(C.panel,.60,.04),panel2:mat(C.panel2,.55,.12),frame:mat(C.frame,.76,.12),tan:mat(C.tan,.82,.03),cream:mat(C.cream,.80,.02),dark:mat(C.dark,.88,.05),metal:mat(C.metal,.72,.22),bronze:mat(C.bronze,.74,.05),wheel:mat(C.wheel,.90,.04),black:mat(C.black,.92,.01),gray:mat(C.gray,.80,.12),orange:mat(C.orange,.70,.03),hubDark:mat(C.hubDark,.88,.05)};
    // chasis expuesto canónico
    const chassis=new THREE.Group();this.group.add(chassis);rbox(3.25,.58,2.25,.12,M.dark,chassis).position.y=-.10;rbox(2.95,.28,2.05,.08,M.metal,chassis).position.y=.25;for(const z of[-.78,.78]){const b=box(3.05,.10,.10,M.gray,chassis);b.position.set(0,-.36,z);}for(const x of[-1.18,1.18]){const b=box(.10,.10,1.85,M.gray,chassis);b.position.set(x,-.36,0);}

    // paneles solares mariposa, 6x4 celdas
    this.deck.position.y=.58;this.group.add(this.deck);const solarMat=new THREE.MeshStandardMaterial({map:solarTexture(),color:0xffffff,roughness:.30,metalness:.035,emissive:0x08172f,emissiveIntensity:.12,flatShading:true});
    const makePanel=(w:number,d:number,x:number,z:number,ry=0,rz=0):THREE.Group=>{const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=ry;g.rotation.z=rz;this.deck.add(g);const frameGeo=new THREE.ExtrudeGeometry(panelShape(w+.08,d+.08,.22),{depth:.07,bevelEnabled:false,steps:1});const frame=add(frameGeo,M.frame,g,false);frame.rotation.x=-Math.PI/2;frame.position.y=.02;const faceGeo=new THREE.ShapeGeometry(panelShape(w,d,.20));normalizePanelUV(faceGeo,w,d);const face=add(faceGeo,solarMat,g,false);face.rotation.x=-Math.PI/2;face.position.y=.100;return g;};
    makePanel(2.35,1.72,0,.05);makePanel(2.25,1.62,-2.18,.56,.06,.015);makePanel(2.30,1.62,-2.20,-1.08,-.04,-.018);makePanel(2.25,1.62,2.18,.56,-.06,-.015);makePanel(2.30,1.62,2.20,-1.08,.04,.018);makePanel(2.12,1.42,0,1.66,0,-.01);this.detachableSolarPanel=makePanel(2.18,1.42,0,-1.63,0,.012);this.detachableBasePosition=this.detachableSolarPanel.position.clone();this.detachableBaseRotation=this.detachableSolarPanel.rotation.clone();this.detachableBaseScale=this.detachableSolarPanel.scale.clone();for(const x of[-1.28,1.28])for(const z of[-.78,.78]){const h=cyl(.10,.10,.26,8,M.metal,this.deck,false);h.position.set(x,.13,z);h.rotation.z=Math.PI/2;}

    // mástil / cámara
    this.mast.position.set(-.72,.58,.22);this.group.add(this.mast);cyl(.46,.46,.20,10,M.bronze,this.mast).position.y=.12;cyl(.39,.39,.22,10,M.cream,this.mast).position.y=.30;rbox(.48,.55,.48,.05,M.gray,this.mast).position.y=.61;rbox(.36,2.18,.36,.045,M.cream,this.mast).position.y=1.83;for(const y of[1.10,1.72,2.34]){const band=rbox(.38,.10,.38,.02,M.bronze,this.mast);band.position.y=y;}cyl(.34,.34,.24,10,M.tan,this.mast).position.y=3.00;const tilt=cyl(.31,.31,1.30,10,M.cream,this.mast);tilt.position.set(0,3.28,0);tilt.rotation.z=Math.PI/2;for(const x of[-.67,.67]){const e=cyl(.35,.35,.16,10,M.tan,this.mast);e.position.set(x,3.28,0);e.rotation.z=Math.PI/2;}this.cameraBar=rbox(1.95,.42,.46,.05,M.tan,this.mast);this.cameraBar.position.set(0,3.80,.02);[-.74,-.38,0,.38,.74].forEach((x,i)=>{const main=i===0||i===4,frame=rbox(main?.34:.30,main?.31:.28,.11,.03,main?M.cream:M.gray,this.mast,false);frame.position.set(x,3.80,.28);const lm=(main?M.black:M.dark).clone();if(main){lm.emissive=new THREE.Color(0x08161c);lm.emissiveIntensity=.12;this.eyeMaterials.push(lm);}const lens=cyl(main?.135:.10,main?.135:.10,.14,10,lm,this.mast,false);lens.position.set(x,3.80,.36);lens.rotation.x=Math.PI/2;});

    // antena
    this.antenna.position.set(.58,.64,.08);this.group.add(this.antenna);cyl(.15,.15,.30,8,M.gray,this.antenna).position.y=.15;cyl(.075,.075,.65,8,M.metal,this.antenna).position.y=.60;cyl(.10,.10,.22,8,M.dark,this.antenna).position.y=1.04;cyl(.06,.06,1.15,8,M.metal,this.antenna).position.y=1.72;cyl(.08,.08,.16,8,M.dark,this.antenna).position.y=2.36;
    // plato
    this.dish.position.set(1.35,.66,-.10);this.group.add(this.dish);cyl(.25,.25,.24,8,M.tan,this.dish).position.y=.12;const stem=rbox(.20,.52,.20,.04,M.cream,this.dish);stem.position.y=.48;cyl(.20,.20,.24,8,M.metal,this.dish).position.y=.82;const dishMat=M.black.clone();dishMat.side=THREE.DoubleSide;const disk=add(new THREE.ConeGeometry(.63,.18,12,1,true),dishMat,this.dish,false);disk.position.set(.10,1.16,.06);disk.rotation.set(Math.PI/2+.12,-.22,.08);const rim=add(new THREE.TorusGeometry(.63,.035,6,12),M.bronze,this.dish,false);rim.position.copy(disk.position);rim.rotation.copy(disk.rotation);const dh=cyl(.075,.075,.16,8,M.metal,this.dish,false);dh.position.set(.10,1.08,-.02);dh.rotation.x=Math.PI/2;
    // instrumentos de cubierta
    const inst=new THREE.Group();inst.position.y=.76;this.group.add(inst);rbox(.56,.30,.46,.05,M.cream,inst).position.set(.38,.18,.34);rbox(.46,.26,.40,.04,M.tan,inst).position.set(.92,.15,.52);cyl(.08,.08,.38,6,M.dark,inst).position.set(-1.35,.20,.78);
    // luces de potencia discretas
    for(const z of[-.48,.48]){const lm=new THREE.MeshStandardMaterial({color:0x49c9d7,emissive:0x49c9d7,emissiveIntensity:1.85,roughness:.35,metalness:.03,flatShading:true});const l=rbox(.11,.18,.28,.02,lm,this.group,false);l.position.set(-1.70,.18,z);this.powerMaterials.push(lm);}
    this.createSuspension(M);this.createWheels(M);this.setPower(1);this.setEyesGlow(.25);
  }

  private createSuspension(M:Record<string,THREE.MeshStandardMaterial>):void{for(const side of[-1,1]){const g=new THREE.Group();this.group.add(g);const bp=new THREE.Vector3(side*1.66,-.12,.10);jointX(.23,.30,M.gray,g,bp);const fe=new THREE.Vector3(side*2.08,-.53,1.05),fh=new THREE.Vector3(side*2.82,-1.05,1.95);beam(bp,fe,.15,M.metal,g);beam(fe,fh,.13,M.metal,g);jointX(.18,.28,M.gray,g,fe);jointX(.17,.28,M.gray,g,fh);const bog=new THREE.Vector3(side*2.04,-.49,-.72),mh=new THREE.Vector3(side*2.62,-1.05,-.03),rh=new THREE.Vector3(side*2.80,-1.05,-1.82);beam(bp,bog,.15,M.metal,g);beam(bog,mh,.13,M.metal,g);beam(bog,rh,.13,M.metal,g);jointX(.20,.28,M.gray,g,bog);jointX(.17,.28,M.gray,g,mh);jointX(.17,.28,M.gray,g,rh);beam(new THREE.Vector3(side*1.90,-.48,1.22),fh,.10,M.cream,g);beam(new THREE.Vector3(side*1.95,-.48,-.82),rh,.10,M.cream,g);}}
  private createWheels(M:Record<string,THREE.MeshStandardMaterial>):void{for(const x of[-2.82,2.82])this.wheelPositions.push(new THREE.Vector3(x,-1.05,1.95),new THREE.Vector3(x,-1.05,-.03),new THREE.Vector3(x,-1.05,-1.82));const wheelR=.66,wheelW=.52,tireGeo=new THREE.CylinderGeometry(wheelR,wheelR,wheelW,12,1,true),sideGeo=new THREE.RingGeometry(.39,.655,12,1),rimGeo=new THREE.TorusGeometry(.425,.060,6,12),hubGeo=new THREE.CylinderGeometry(.285,.285,wheelW+.06,12),capGeo=new THREE.CylinderGeometry(.115,.115,wheelW+.11,8);for(const p of this.wheelPositions){const wg=new THREE.Group();wg.position.copy(p);this.group.add(wg);this.wheelGroups.push(wg);const tire=add(tireGeo,M.wheel,wg);tire.rotation.z=Math.PI/2;for(const side of[-1,1]){const sw=add(sideGeo,M.wheel,wg,false);sw.rotation.y=Math.PI/2;sw.position.x=side*(wheelW/2+.006);const rim=add(rimGeo,M.orange,wg,false);rim.rotation.y=Math.PI/2;rim.position.x=side*(wheelW/2+.020);}const hub=add(hubGeo,M.hubDark,wg,false);hub.rotation.z=Math.PI/2;const core=add(capGeo,M.metal,wg,false);core.rotation.z=Math.PI/2;for(let i=0;i<12;i++){const a=i/12*Math.PI*2;for(const side of[-1,1]){const tread=box(wheelW*.58,.145,.205,M.gray,wg,false);tread.position.set(side*wheelW*.19,Math.cos(a)*(wheelR+.040),Math.sin(a)*(wheelR+.040));tread.rotation.set(-a,0,side*.28);}}}}

  advance(speed:number,dt:number):void{this.group.position.x+=speed*dt*2.2;this.animateWheels(speed,dt);}
  animateWheels(speed:number,dt:number):void{this.wheelSpin-=speed*dt*3.7;this.wheelGroups.forEach(w=>w.rotation.x=this.wheelSpin);}
  setPower(amount:number):void{const p=THREE.MathUtils.clamp(amount,0,1);this.powerMaterials.forEach(m=>{m.color.copy(new THREE.Color(0x20242c).lerp(new THREE.Color(0x49c9d7),p));m.emissive.copy(new THREE.Color(0x071014).lerp(new THREE.Color(0x49c9d7),p));m.emissiveIntensity=.02+1.82*p;});}
  setEyesGlow(amount:number):void{const p=THREE.MathUtils.clamp(amount,0,1);this.eyeMaterials.forEach(m=>{m.emissive.copy(new THREE.Color(0x08161c).lerp(new THREE.Color(0x39cfe5),p));m.emissiveIntensity=.06+1.15*p;});}
  pointMast(yaw:number,pitch:number):void{this.mast.rotation.y=yaw;this.mast.rotation.x=pitch;}
  pointDish(amount:number):void{this.dish.rotation.y=amount;}
  getWorldWheelPosition(index:number,target=new THREE.Vector3()):THREE.Vector3{const i=THREE.MathUtils.clamp(index,0,this.wheelGroups.length-1);return this.wheelGroups[i].getWorldPosition(target);}
  getWorldEyePosition(target=new THREE.Vector3()):THREE.Vector3{return this.cameraBar.getWorldPosition(target);}
  getWorldAntennaTip(target=new THREE.Vector3()):THREE.Vector3{target.set(0,2.44,0);return this.antenna.localToWorld(target);}
  detachSolarPanelTo(parent:THREE.Object3D):void{this.detachableSolarPanel.updateMatrixWorld(true);parent.attach(this.detachableSolarPanel);}
  restoreSolarPanel():void{if(this.detachableSolarPanel.parent!==this.deck)this.deck.attach(this.detachableSolarPanel);this.detachableSolarPanel.position.copy(this.detachableBasePosition);this.detachableSolarPanel.rotation.copy(this.detachableBaseRotation);this.detachableSolarPanel.scale.copy(this.detachableBaseScale);this.detachableSolarPanel.visible=true;}
  resetDynamicPose():void{this.wheelSpin=0;this.wheelGroups.forEach(w=>w.rotation.set(0,0,0));this.mast.rotation.set(0,0,0);this.dish.rotation.set(0,0,0);this.antenna.rotation.set(0,0,0);this.restoreSolarPanel();this.setPower(1);this.setEyesGlow(.25);}
}
